# Generated by Django 2.2 on 2024-07-15 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCatProd', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProduct', models.CharField(help_text='Nombre del producto', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del producto', max_digits=10)),
                ('imagen1', models.ImageField(blank=True, help_text='Imagen del producto frontal', null=True, upload_to='tienda/%Y/%m/%d/')),
                ('imagen2', models.ImageField(blank=True, help_text='Imagen del producto trasera', null=True, upload_to='tienda')),
                ('imagen3', models.ImageField(blank=True, help_text='Imagen del producto lateral', null=True, upload_to='tienda')),
                ('descuento', models.IntegerField(default=0, help_text='Cantidad disponible en stock')),
                ('sku', models.CharField(help_text='Número único del producto', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.CategoriaProd')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
