# Generated by Django 2.2 on 2024-07-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen1',
            field=models.ImageField(blank=True, help_text='Imagen del producto frontal', null=True, upload_to='miMuebleria/media/tienda/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(blank=True, help_text='Imagen del producto trasera', null=True, upload_to='miMuebleria/media/tienda/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen3',
            field=models.ImageField(blank=True, help_text='Imagen del producto lateral', null=True, upload_to='miMuebleria/media/tienda/%Y/%m/%d/'),
        ),
    ]
