# Generated by Django 2.2 on 2024-07-16 19:46

from django.db import migrations, models
import tienda.models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20240715_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen1',
            field=models.ImageField(blank=True, help_text='Imagen del producto frontal', null=True, upload_to=tienda.models.upload_to),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(blank=True, help_text='Imagen del producto trasera', null=True, upload_to=tienda.models.upload_to),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen3',
            field=models.ImageField(blank=True, help_text='Imagen del producto lateral', null=True, upload_to=tienda.models.upload_to),
        ),
    ]
