# Generated by Django 2.2 on 2024-07-22 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0004_auto_20240718_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ventas_totales',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReporteVentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('total_venta', models.FloatField()),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Venta',
                'verbose_name_plural': 'Reportes de Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
    ]
