# Generated by Django 2.2 on 2024-07-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_auto_20240722_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporteventas',
            options={'verbose_name': 'Reporte de Ventas', 'verbose_name_plural': 'Reportes de Ventas'},
        ),
        migrations.RenameField(
            model_name='reporteventas',
            old_name='fecha_venta',
            new_name='fecha',
        ),
        migrations.AlterField(
            model_name='reporteventas',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reporteventas',
            name='total_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
